import { cn } from "@/lib/utils";
import { ThemeProvider } from "@components/theme-provider";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Translator App",
	description: "Generated by translator app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="pt-BR">
			<body
				className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
					storageKey="translator-app-theme"
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
};

export default RootLayout;
